# Generated by Django 5.0.6 on 2026-09-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_logs', '0002_inquirylog_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirylog',
            name='feedback',
            field=models.CharField(blank=True, choices=[('up', 'Helpful'), ('down', 'Not helpful')], max_length=4, null=True),
        ),
    ]
